### ISSUE TITLE
Full Keyboard does not work properly

### ISSUE THREAD

**Issue by Benjammin-n215** [Jax-Core/Keystrokes#2]
When you use the full board settings, none of the bottom row keys (Z-M) don't appear to work.

Would also love to see support for shift, tab, control, spacebar, and mouse accelerometer/buttons for fullboard. Otherwise, fantastic overlay.

**Comment by EnhancedJax** [comment]
The skin currently isn't fully functional as of now due to changes in core structure. I'll try to repair it after the next core update a sub as possible.
